[[HDF5]]
arch = "aarch64"
git-tree-sha1 = "f19ea8dd5a61be14f3b49358f64800662baa48ee"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[HDF5.download]]
    sha256 = "bf31676341b1b4d607452531a0a803b57647aee0a0828727d48caea03136f464"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+0/HDF5.v2.0.0.aarch64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[HDF5]]
arch = "aarch64"
git-tree-sha1 = "3213a383dfffdbdf02f6f9d33782706d9cb98495"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[HDF5.download]]
    sha256 = "19b47754f8aab88289f4a220595d6d1b74d028b63c0b32ec4a064df5ad2a793a"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+0/HDF5.v2.0.0.aarch64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[HDF5]]
arch = "aarch64"
git-tree-sha1 = "7ce7b7c8e66b91eb53a7988a1708faee731f02d9"
lazy = true
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "macos"

    [[HDF5.download]]
    sha256 = "4b91e102941c2b1e1c39d3f64533002d53434389bc8a14c1c704fdf1dea6ec5e"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+0/HDF5.v2.0.0.aarch64-apple-darwin-libgfortran5-mpi+openmpi.tar.gz"
[[HDF5]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "40a4b407db44e5b1a513d115d1d3f4976db490d8"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[HDF5.download]]
    sha256 = "344f988d319a0244211b8ad7a353f4985c621086e8c0371e5d91be951911f174"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+0/HDF5.v2.0.0.aarch64-linux-gnu-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[HDF5]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a5beeafe0ba0da840bb92c862da3af1d4b9eb221"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[HDF5.download]]
    sha256 = "fc7b34e65f948f1355eeb5bc24ba5128598c643f194eabcd20dd8f3f46cbe44f"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+0/HDF5.v2.0.0.aarch64-linux-gnu-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[HDF5]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed9fd3a211dd8949ae5d44fd6bf56b9d32b72656"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[HDF5.download]]
    sha256 = "844dc7c5ea0d61b42b850cc0ea21edb6826683564ea141a49b316035a0dda74c"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+0/HDF5.v2.0.0.aarch64-linux-gnu-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[HDF5]]
arch = "aarch64"
git-tree-sha1 = "60b75966007c083e47f4c65fcf4d23589c70eebc"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "freebsd"

    [[HDF5.download]]
    sha256 = "a1ce74d97ef348835344da083d9d61c774c4dd328e5d9b74e9af3081d2e538d7"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+0/HDF5.v2.0.0.aarch64-unknown-freebsd-libgfortran5-mpi+mpich.tar.gz"
[[HDF5]]
arch = "aarch64"
git-tree-sha1 = "e28bd78243926a27e1d5387a3f486930fe7d5345"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "freebsd"

    [[HDF5.download]]
    sha256 = "ca3ce60fe6d389c26602bb69712ae4dadb13c68c43e59675ded1badee015658f"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+0/HDF5.v2.0.0.aarch64-unknown-freebsd-libgfortran5-mpi+mpitrampoline.tar.gz"
[[HDF5]]
arch = "aarch64"
git-tree-sha1 = "b5f5931735b0f5c110e7a5cc8bd58a14047f894c"
lazy = true
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "freebsd"

    [[HDF5.download]]
    sha256 = "bcd46ef8b7e4168d1551cba61cff7bd72c31c9306848987ab9444eecf21f2aef"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+0/HDF5.v2.0.0.aarch64-unknown-freebsd-libgfortran5-mpi+openmpi.tar.gz"
[[HDF5]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "23038935ce4e3b7875a8038cea152c64c081fe8f"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[HDF5.download]]
    sha256 = "4106baecbe25de861dc8742cea7ab7bbe5314a7567da104a08ff304c99db8ebc"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+0/HDF5.v2.0.0.armv6l-linux-gnueabihf-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[HDF5]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "16aee93f4b10b0fa9e916d063a6cd9419add89d6"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[HDF5.download]]
    sha256 = "e3ca74b2f6a6f5a9681d7272f39992b5e551ed8122ee81ec7bb3e443f5a0cd25"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+0/HDF5.v2.0.0.armv6l-linux-gnueabihf-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[HDF5]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fe59d8827b870172da941a7549b927160f753d2b"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[HDF5.download]]
    sha256 = "422bf337f7cce0a823372bab97f4cd72e72922964c4d5bbeb98238d622e06dda"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+0/HDF5.v2.0.0.armv7l-linux-gnueabihf-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[HDF5]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f28494b01d7c317c92cb2cfe09e1fd530aaca12c"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[HDF5.download]]
    sha256 = "48d3d7b36fed1c0f016df849fc09473768d7ba467baebe4e27e700a447dd0fe5"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+0/HDF5.v2.0.0.armv7l-linux-gnueabihf-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[HDF5]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0a7fb5a208de76304f22499419ab91bd4624ee58"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[HDF5.download]]
    sha256 = "cfc38ac43e683148b80a7ccd20aa00150f7d58f7994d4dbbf0e0406bcb7d8e66"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+0/HDF5.v2.0.0.armv7l-linux-gnueabihf-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[HDF5]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6bfd545f24f3de05ef61df89cea10904c50d5c70"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[HDF5.download]]
    sha256 = "82b9d439f09d7af7cf326dd131f9a67de727b126576b2df2edcabb4994d8b411"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+0/HDF5.v2.0.0.i686-linux-gnu-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[HDF5]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a937da7933e9f63ee8fb8183e72e75f02cae2dd7"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[HDF5.download]]
    sha256 = "1966a1f40d069317d393829f1f7a88347569de0bb4e69eb26ae5c2e771e6339d"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+0/HDF5.v2.0.0.i686-linux-gnu-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[HDF5]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5952630eacefcf710d1d1860b6a87fd7c9007b63"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[HDF5.download]]
    sha256 = "3ef6c9e6718d8dbc943b7c992cb018aaba79f7fd488d80a52f837e1d7bbc94dd"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+0/HDF5.v2.0.0.i686-linux-gnu-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[HDF5]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed8c55ddba8c54a885d0ca7a4bd4974508999289"
lazy = true
libgfortran_version = "5.0.0"
mpi = "microsoftmpi"
os = "windows"

    [[HDF5.download]]
    sha256 = "f8abdec495172644cd0e80f1f9efedd0466f40452544b77666ac80127fc586f6"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+0/HDF5.v2.0.0.i686-w64-mingw32-libgfortran5-cxx11-mpi+microsoftmpi.tar.gz"
[[HDF5]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4cb19ecb738d541434e22a421a775ccea3106cb5"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[HDF5.download]]
    sha256 = "583f8f89565738a7506f81418e8ef7ec61ba8255588842a8f7eae58eca277e00"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+0/HDF5.v2.0.0.powerpc64le-linux-gnu-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[HDF5]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "887f55c97e7e7ee8095dc1aeb60a4e0049ceebe8"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[HDF5.download]]
    sha256 = "cd025a7c01168f56ac24a4842ea7ee154da49546ecd39d2f03422e5dae9c84ae"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+0/HDF5.v2.0.0.powerpc64le-linux-gnu-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[HDF5]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c982793a673c2b73b1ca2353d5144621e0d253df"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[HDF5.download]]
    sha256 = "c7ec7bbe3a2d89a955971f73216c8c1a27d624b9185f5062f1f9895361b40069"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+0/HDF5.v2.0.0.powerpc64le-linux-gnu-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[HDF5]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6dac561dc9f0b6aa22475b25325c65d2871934e7"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[HDF5.download]]
    sha256 = "ff702d0e9bbf6e983ee28f1d8916ecd2821f02884866ae2e47e9f329dece783c"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+0/HDF5.v2.0.0.riscv64-linux-gnu-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[HDF5]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c650e23a72391abe3f3497f364bf63043f7697cb"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[HDF5.download]]
    sha256 = "5b6d3a40401901013196ca222aa96e6ea63dc22c1f4464cd46883b24872e5129"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+0/HDF5.v2.0.0.riscv64-linux-gnu-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[HDF5]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c3eb387bbf1d8b65f62aedcb76ce3dee82199b3"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[HDF5.download]]
    sha256 = "ff348f8d6388d19590c05601390b4668f9258618a35b1fd7928660a80f2e9873"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+0/HDF5.v2.0.0.riscv64-linux-gnu-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[HDF5]]
arch = "x86_64"
git-tree-sha1 = "53e3d87b3143fa0ff9edff41f45496825221f7c5"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[HDF5.download]]
    sha256 = "5a78ca9a10b04ce0c1fdadcfb0809834f21dabda88d600cf074833ccbf7eac10"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+0/HDF5.v2.0.0.x86_64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[HDF5]]
arch = "x86_64"
git-tree-sha1 = "009ed2a00f798e9b2389d6af06e7ad5ece94a075"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[HDF5.download]]
    sha256 = "1c5943ab46557760adec60c95721abd36f7eacf6ea08095db152aa84cff73884"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+0/HDF5.v2.0.0.x86_64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[HDF5]]
arch = "x86_64"
git-tree-sha1 = "af13c84277193c63aad0b38fd0e7857f01736371"
lazy = true
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "macos"

    [[HDF5.download]]
    sha256 = "caccefa0aac9370614c42c623a39cacfa109d07abce90e12a3e70ebd3eca651a"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+0/HDF5.v2.0.0.x86_64-apple-darwin-libgfortran5-mpi+openmpi.tar.gz"
[[HDF5]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7279c1c32e98f690ae8b053f8a6ec5c7ba35f7e7"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[HDF5.download]]
    sha256 = "e0088008864a0c76d35f74acf71fb55101d3d648440898f29fd12da2507e34d5"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+0/HDF5.v2.0.0.x86_64-linux-gnu-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[HDF5]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c4451e8d7b7c74a15ee3fe87e5f5aedf815c928"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[HDF5.download]]
    sha256 = "6a4dde273db3512f1be4833052977c4ec427a81d1491c62ee9c0321862f972f1"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+0/HDF5.v2.0.0.x86_64-linux-gnu-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[HDF5]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db08d507e8746b871466c93ea83dd89498a2e11a"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[HDF5.download]]
    sha256 = "91c1d6acd7cdcc6042f84c013cf092f22745a47648fa58f1d275f7b1d9a697b2"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+0/HDF5.v2.0.0.x86_64-linux-gnu-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[HDF5]]
arch = "x86_64"
git-tree-sha1 = "f2b9d4e644fe5f672923dd569fe9b090052e39c8"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "freebsd"

    [[HDF5.download]]
    sha256 = "4e30efd1362d9b1cd636a0cba28890dbf8ce0e066c8047d8d78f9f16013241c8"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+0/HDF5.v2.0.0.x86_64-unknown-freebsd-libgfortran5-mpi+mpich.tar.gz"
[[HDF5]]
arch = "x86_64"
git-tree-sha1 = "7e79a741db16e8c65898f7658f38ac9a01d8d32f"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "freebsd"

    [[HDF5.download]]
    sha256 = "8f02422c1f5024cd80351c042f357d16a2aa724046f2c95f6db13d312d9bcc65"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+0/HDF5.v2.0.0.x86_64-unknown-freebsd-libgfortran5-mpi+mpitrampoline.tar.gz"
[[HDF5]]
arch = "x86_64"
git-tree-sha1 = "cd5e8e388b7fefac2ce5bbefe0a71a155aea5250"
lazy = true
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "freebsd"

    [[HDF5.download]]
    sha256 = "b7578bb83fdb208f4a1515ae48ae152225a82bf7d9c23e5ae86bb477cd4aa21d"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+0/HDF5.v2.0.0.x86_64-unknown-freebsd-libgfortran5-mpi+openmpi.tar.gz"
[[HDF5]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b1dc244c8966ef06e099c2a6c9efac83b590e3f3"
lazy = true
libgfortran_version = "5.0.0"
mpi = "microsoftmpi"
os = "windows"

    [[HDF5.download]]
    sha256 = "ef8f30bd733ccb2c375d9edc8cdf8dad18a5d9c0342ccc4f8898140296e1a6fc"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+0/HDF5.v2.0.0.x86_64-w64-mingw32-libgfortran5-cxx11-mpi+microsoftmpi.tar.gz"
