[[HDF5]]
arch = "aarch64"
git-tree-sha1 = "8d09b56228bbba637c2aadfa8e24b689800dac82"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[HDF5.download]]
    sha256 = "14aaa663d75e441be3da5438f488f77596b9cb2690377807a60de7a20b7558c5"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.aarch64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[HDF5]]
arch = "aarch64"
git-tree-sha1 = "d40b2ecab130c96b291b9bc1f0b946f500b61630"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[HDF5.download]]
    sha256 = "bab375af1ae6bc511bc44003b05e4534b0623c9badec561e1d5495096f915ecf"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.aarch64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[HDF5]]
arch = "aarch64"
git-tree-sha1 = "0b24867eacec88f32b2789ffc669feec7b8b6315"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "macos"

    [[HDF5.download]]
    sha256 = "252b9417ee8b0fc195a39b40cf932e0423eafd20b2f1eb808d30ae89a0d13bde"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.aarch64-apple-darwin-libgfortran5-mpi+openmpi.tar.gz"
[[HDF5]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c617fbc7bb46d4073b8472ad1582166d25348498"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[HDF5.download]]
    sha256 = "266d52708dac61235a432c4ecfd9cfa1fef154478d8efcf3898f9803ec93f53d"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.aarch64-linux-gnu-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[HDF5]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f6d3b9b9910a4f6cf6105a02882aeccbae4e501a"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[HDF5.download]]
    sha256 = "3e7f38ff91b7fa183853d7fa7fc5df423e0f6f0a06f6c22c10e63c009fbc76f3"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.aarch64-linux-gnu-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[HDF5]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a03311b37d4b77e6483efb89e7d773227879b16"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[HDF5.download]]
    sha256 = "7b53495f293c3ca4fa0da2013fbc2a88678ac6e00f0657fd3743dfe4f9225eb5"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.aarch64-linux-gnu-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[HDF5]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b591328189f70b05ecb2e8edeb9ea3d28be5d63"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[HDF5.download]]
    sha256 = "97e9f1dcdac1a890ad7f44a423486b5fd9a06846d516d5028000948aa98a82f5"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.aarch64-linux-musl-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[HDF5]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4371e45d5191db88d24896c60defa16239fd3536"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[HDF5.download]]
    sha256 = "aa4542c75744704668ab7c6729297dc363d98390a692573699b2a1bb0dcf6888"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.aarch64-linux-musl-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[HDF5]]
arch = "aarch64"
git-tree-sha1 = "039377dd70ef935cb945afc4a476bc06723b77f5"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "freebsd"

    [[HDF5.download]]
    sha256 = "b2b8551a08f0054c37b0151121612b21bee1719dda125c72fa9ec2f26630b012"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.aarch64-unknown-freebsd-libgfortran5-mpi+mpich.tar.gz"
[[HDF5]]
arch = "aarch64"
git-tree-sha1 = "71adc62ba4d49fb5399389e2e1fa18440c2c8d73"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "freebsd"

    [[HDF5.download]]
    sha256 = "642cf1e6f61313c0d0c16f8951b7172aa3c9d4e5fd1b21b1ed24df0b24b0e244"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.aarch64-unknown-freebsd-libgfortran5-mpi+mpitrampoline.tar.gz"
[[HDF5]]
arch = "aarch64"
git-tree-sha1 = "93d198fa01ed0c8a9aa02af3a086868f108b57b5"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "freebsd"

    [[HDF5.download]]
    sha256 = "c573f9f30b9ff5f04a6fa9b7dc7ddb4cc361c9f11d3360b183fdbba0cce49777"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.aarch64-unknown-freebsd-libgfortran5-mpi+openmpi.tar.gz"
[[HDF5]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5508f7a391bd379e9ee20ae6c20a0b8171522fdf"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[HDF5.download]]
    sha256 = "c9cd4718704e77549b9ca14ef1e9566e58974edac12df48a215646ace788c1c8"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.armv6l-linux-gnueabihf-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[HDF5]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7b8c1d064a29d3b66c0003e5c07306bcbf4c823f"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[HDF5.download]]
    sha256 = "efab222a2244b90ce7d8a73a18620064f8a5c578dca5fe889685e6b54c8f6b45"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.armv6l-linux-gnueabihf-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[HDF5]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2c0081076c891e5466c1a7e0f01c706a3326e2bd"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[HDF5.download]]
    sha256 = "f1a195f77fb8adddccb7b599d116e52353dc4e72f62f0151863d3d18ad53096e"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.armv6l-linux-musleabihf-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[HDF5]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7470e5f25b70eb8bddae695117f9bba4b9cdd567"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[HDF5.download]]
    sha256 = "ecc0633923bff8b945cfad280a9e05b5bb6911a6d07ecf0eed1abb2ea3b71525"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.armv6l-linux-musleabihf-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[HDF5]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6aa9c1308e8607fa37c624d012cd3f2110eb1658"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[HDF5.download]]
    sha256 = "6bfd88d6748c37f94133ab1e7df108bde5fe5af3cdf2205d93e11acb16df38df"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.armv7l-linux-gnueabihf-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[HDF5]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a1533844695dca90b9d04e7e5f031884d7f519aa"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[HDF5.download]]
    sha256 = "6604b248f7211b2131640e5f511f66d4a508e6a0a530be6c30c27bee6bdf038c"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.armv7l-linux-gnueabihf-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[HDF5]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "372f57552d9e03f6f5ee9746ec647d53c577cb18"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[HDF5.download]]
    sha256 = "2fc70c7b18884d054614105676c1cd6784d23e8c7564110c077ee9a564d1223f"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.armv7l-linux-gnueabihf-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[HDF5]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc8723934a8638b522e6d13c38e5db009902510a"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[HDF5.download]]
    sha256 = "0cb6345036d9850ae6fc9e89dffc1e05b431fe66371f54b1bed19eab1262f4a2"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.armv7l-linux-musleabihf-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[HDF5]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2fb32fb0b1e1d5ae7807a8ecf6c569db2a9b1220"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[HDF5.download]]
    sha256 = "4ae0bed82e57000ed9399454cc7775f8206a72b2e9c5aaaafc01bc8d946bbd3b"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.armv7l-linux-musleabihf-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[HDF5]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "307ae4bf31356040d1741c48cd27ffed1e93840f"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[HDF5.download]]
    sha256 = "f9a536ce25e2beb7c394a303b4cc9c833a94099cedbc5fb9aa1a07197b80e131"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.i686-linux-gnu-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[HDF5]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f3a4e7f7cdd730799beb85086ae6042df4854949"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[HDF5.download]]
    sha256 = "90697817dc0cf117e7ad749e170adaa65b1fca855bc81087cb8aee3ed9ff177a"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.i686-linux-gnu-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[HDF5]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "71ee97453e77f0b07b76c0b1160d07e1bb0cc23a"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[HDF5.download]]
    sha256 = "a29f6a538795c8e96db743eee8eccfdd47f14d4943661ccb494834bdfe21efb1"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.i686-linux-gnu-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[HDF5]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2efa2f9e574c23e5bed93e1ff384832322667953"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[HDF5.download]]
    sha256 = "7aafa96cbda86fb143d674e27e6b1310ce932837686d0cd5df0c964808048512"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.i686-linux-musl-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[HDF5]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "49483b9de8a9e55de78b0ab130ac6a5ec8ce01e5"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[HDF5.download]]
    sha256 = "536d92be258a3298f5ac3eb421e0d2a152dcc9ea3ed87f3026e22e5a794f93c3"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.i686-linux-musl-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[HDF5]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12f41df797b34eb571e48321a13083a43023a888"
libgfortran_version = "5.0.0"
mpi = "microsoftmpi"
os = "windows"

    [[HDF5.download]]
    sha256 = "873db6d417fb9f9d48c83afacf07c57144e631ac113f3f4296c2048882e25a1e"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.i686-w64-mingw32-libgfortran5-cxx11-mpi+microsoftmpi.tar.gz"
[[HDF5]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "58c130c23e7a73fc19f03b255deeec13104c2c43"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[HDF5.download]]
    sha256 = "8d41fd62d62e0e7f7013f6b12b3b7ddb4f636c71ecab50b5c49ab7c07d23db3e"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.powerpc64le-linux-gnu-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[HDF5]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "59cfa7665393896a5703776fa2bcfab76ed74b79"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[HDF5.download]]
    sha256 = "f8146ab194bf6cde65600f579959f6c6b92573b5f49a6d80a2380fa67505c10d"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.powerpc64le-linux-gnu-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[HDF5]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d5c62c4586c387ae2737c0080f9ecda377f55413"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[HDF5.download]]
    sha256 = "0aa355cd60efbb48a3d82e2058f7381677b465d8e97c7f760d75a57fb3bac1ff"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.powerpc64le-linux-gnu-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[HDF5]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a667d2dcbf5ecbd8235849df85b732e1b6846ab1"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[HDF5.download]]
    sha256 = "b2b5833e0040519198258aecd85110a72432753705eedb4b0213970a283489a8"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.riscv64-linux-gnu-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[HDF5]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1dc737e53841d6f13b0303b242c4a7da020593bd"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[HDF5.download]]
    sha256 = "b2f4cd072da1e4cab9af89a4ebfc0845b2dd091d80b29bb5996f4b5500bb0da3"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.riscv64-linux-gnu-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[HDF5]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0183bf2122e9db0b9460add877fa162df51259cb"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[HDF5.download]]
    sha256 = "40a1b814349878eada2494757bf1585b171cbe39bd5cbc7c344e0582a8eb1aa6"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.riscv64-linux-gnu-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[HDF5]]
arch = "x86_64"
git-tree-sha1 = "ce611704093bfffd73769f88b6eca89620d87ec3"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[HDF5.download]]
    sha256 = "cd1ed29ef1ed1ac369003c2d3e5e9faf5d42715ef6a7bd6962b81fe7160306ea"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.x86_64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[HDF5]]
arch = "x86_64"
git-tree-sha1 = "7d0c23d0c5c71f6b6da009797e78d525f7b301c9"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[HDF5.download]]
    sha256 = "aba39d63ff276ae9ba0d08f8f91c6711a8d9af73fb225e2ad7b66e59a5a2292b"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.x86_64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[HDF5]]
arch = "x86_64"
git-tree-sha1 = "0064a363c5c5a4af0fc0461a721db3347b917787"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "macos"

    [[HDF5.download]]
    sha256 = "86fb8abc6bad00066717a03ff62c88429b2d8acab89a9fad54b524044831148e"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.x86_64-apple-darwin-libgfortran5-mpi+openmpi.tar.gz"
[[HDF5]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "394daee0609ac6d7eec2a7b6c108a597b946f166"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[HDF5.download]]
    sha256 = "24ab84b1fd0eb0b7b087ef15265744a13c55db1e54020863d63eb231af81cf4c"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.x86_64-linux-gnu-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[HDF5]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eac51c9c81d51134403c15ed50c3c2b999478ddf"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[HDF5.download]]
    sha256 = "924e69e9d204fab8439f202d646d7c4fbfafe3e3570c11e92cc5b39071706ee9"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.x86_64-linux-gnu-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[HDF5]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "226c8797b9bca0af773340c0318967fe4ba7802b"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[HDF5.download]]
    sha256 = "291baed039eeaa107c99fa119272824a82e798f4e8792df8dc462e9b0e15e94e"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.x86_64-linux-gnu-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[HDF5]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "efd5f0bf19a810ca94b6ebfafa98f6b61c43d6c3"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[HDF5.download]]
    sha256 = "db4e73c62f8738987d57b8803c6c5e843475d7519d33e05776889239a4ada7c6"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.x86_64-linux-musl-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[HDF5]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed0a49196d5184dcea4958cbbc645eb402a0922a"
libc = "musl"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[HDF5.download]]
    sha256 = "1bd40544b08ddb0499ed377d1172016a628f54e288969592440e5eccd2a952f3"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.x86_64-linux-musl-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[HDF5]]
arch = "x86_64"
git-tree-sha1 = "4c60ca37949f5a0c74b2e2954c5969a01497265c"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "freebsd"

    [[HDF5.download]]
    sha256 = "0aa74f199a009465dcad44d20a2ae63b5e696e4c0ecb86fb40ef59d25cbb805f"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.x86_64-unknown-freebsd-libgfortran5-mpi+mpich.tar.gz"
[[HDF5]]
arch = "x86_64"
git-tree-sha1 = "9d0e98ced34292c51ad645392529bf71448390e9"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "freebsd"

    [[HDF5.download]]
    sha256 = "06e5f006b7859dfb5a9bdb3315e1c6a9f5004d239283a2770ee48db126a91019"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.x86_64-unknown-freebsd-libgfortran5-mpi+mpitrampoline.tar.gz"
[[HDF5]]
arch = "x86_64"
git-tree-sha1 = "424b59ad9e113cc73ef932a2583feacd5d8999c9"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "freebsd"

    [[HDF5.download]]
    sha256 = "1102b27406de61c81b21cbd465bccbed97e1d113770800355a696d59f7f15551"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.x86_64-unknown-freebsd-libgfortran5-mpi+openmpi.tar.gz"
[[HDF5]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "90f8e338c26488f5a16607df34157dbb58dc7ca3"
libgfortran_version = "5.0.0"
mpi = "microsoftmpi"
os = "windows"

    [[HDF5.download]]
    sha256 = "ebae9be9d176710791421195234ba6955232c188d0d3a901c8c662ed4ac47b77"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.1+0/HDF5.v2.0.1.x86_64-w64-mingw32-libgfortran5-cxx11-mpi+microsoftmpi.tar.gz"
