[[HDF5]]
arch = "aarch64"
git-tree-sha1 = "f4caf08ebcc464411b7c4d7822c34e024ffaff4d"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[HDF5.download]]
    sha256 = "17b8e2f1087f1ae63dd67ad25660a4083d2a0a4e6db89575dbf5718ea1ba4783"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+1/HDF5.v2.0.0.aarch64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[HDF5]]
arch = "aarch64"
git-tree-sha1 = "b5422884b3acaf9d4afdb260e2c6085dcbfbd1a2"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[HDF5.download]]
    sha256 = "2be6595f54e1bf099d65d3fe94ea9cf5d85ff70c069a374b0a0b18a310bceccb"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+1/HDF5.v2.0.0.aarch64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[HDF5]]
arch = "aarch64"
git-tree-sha1 = "7dd284d3710e6b966de1f25525fd9b5d927cfaa4"
lazy = true
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "macos"

    [[HDF5.download]]
    sha256 = "eccafc06fc487053475608ada4541cc74a4a7dacf4c54e62e64d4594d18a3ac1"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+1/HDF5.v2.0.0.aarch64-apple-darwin-libgfortran5-mpi+openmpi.tar.gz"
[[HDF5]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3cfe416037aee77307499eba661daa420e498efc"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[HDF5.download]]
    sha256 = "39e5733cef49f001f6d73d99b4642093a5e1cf67a03cd2895d9b7ea843e51743"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+1/HDF5.v2.0.0.aarch64-linux-gnu-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[HDF5]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c202e3438e05c54525173977bc1928c8fcca13cb"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[HDF5.download]]
    sha256 = "ace99ebc108d3bb7520b551fb2660dd321258703442f87530714fd57d22d9893"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+1/HDF5.v2.0.0.aarch64-linux-gnu-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[HDF5]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5eee05d7cac6c37b88b6f2c0d3bbbf75de4428c1"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[HDF5.download]]
    sha256 = "82c2eafb168dcbb1201908520593e11d5155c7247fb57fc86c1810d15b79876d"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+1/HDF5.v2.0.0.aarch64-linux-gnu-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[HDF5]]
arch = "aarch64"
git-tree-sha1 = "ede56f34d83ea31f7b65cbdd76da59933300653a"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "freebsd"

    [[HDF5.download]]
    sha256 = "d48a15c541ab2fa98055812cf89cc60edd952cc51e0a1b38cac51afd47f56877"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+1/HDF5.v2.0.0.aarch64-unknown-freebsd-libgfortran5-mpi+mpich.tar.gz"
[[HDF5]]
arch = "aarch64"
git-tree-sha1 = "5006eaed9d35f41f40fdd0a17831f5cbf27e1f0b"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "freebsd"

    [[HDF5.download]]
    sha256 = "7faccd12530b2998216ee58dcefe30dd0d8d7cf7df67b152c4abea427fb14989"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+1/HDF5.v2.0.0.aarch64-unknown-freebsd-libgfortran5-mpi+mpitrampoline.tar.gz"
[[HDF5]]
arch = "aarch64"
git-tree-sha1 = "fc4a9eaab9b8c91c2e1d1c60eb6292bf42c928b7"
lazy = true
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "freebsd"

    [[HDF5.download]]
    sha256 = "b8a530d088b8f38b89b2eb3c20ad3eee51d9575d4c161f37f0efaeab56f71776"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+1/HDF5.v2.0.0.aarch64-unknown-freebsd-libgfortran5-mpi+openmpi.tar.gz"
[[HDF5]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "acbebcf51426bb90bf106211d79b31cc880e6473"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[HDF5.download]]
    sha256 = "90d89f6b12a609bed47b33d525c47840586edbb9d38d390887e4fc3423c7b7a3"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+1/HDF5.v2.0.0.armv6l-linux-gnueabihf-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[HDF5]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "917e0931b0b8b0119a0bd857c16b13f2853e8fd8"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[HDF5.download]]
    sha256 = "c6b6f775e85ecfdf8168c0411a30f397df66adf5d8bed180685dfb6fe8970541"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+1/HDF5.v2.0.0.armv6l-linux-gnueabihf-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[HDF5]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "05bfbd029656f400a2b450595d3927113406543f"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[HDF5.download]]
    sha256 = "d34e1f3695f9348d0d6dfda9838df534267b8054fbb09c4055a6aa0afda9c609"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+1/HDF5.v2.0.0.armv7l-linux-gnueabihf-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[HDF5]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a6725f405679522177d00074a743012783a9e131"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[HDF5.download]]
    sha256 = "5b677903df0e35879670e5eab8ee99effb62670ed2c1269dad3208b17831602c"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+1/HDF5.v2.0.0.armv7l-linux-gnueabihf-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[HDF5]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca0e074e2f07a9a96b757f557796120ac9f08f32"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[HDF5.download]]
    sha256 = "006ade9e88957931b8a4a2c7856838e77caddf53da8a427f4864c20f10c2179d"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+1/HDF5.v2.0.0.armv7l-linux-gnueabihf-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[HDF5]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b869f49e42f4ce5f139f9d7f91a967671540964"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[HDF5.download]]
    sha256 = "4e9eb58ddf92236b9f526ae6aa72a1214182ee035a9b7f12a2509e02d2e8adf9"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+1/HDF5.v2.0.0.i686-linux-gnu-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[HDF5]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e38901c51cfd66eff0b14ad5ebddf1d8ed1e26a2"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[HDF5.download]]
    sha256 = "346bce0df4ac59de6a374d0b2eddae30c68ec4e78a3cb3ec247598dde8d18088"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+1/HDF5.v2.0.0.i686-linux-gnu-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[HDF5]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c81867b66edd8d1bfe3cbf1866df0d609d4ab95"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[HDF5.download]]
    sha256 = "395385a1b32f78c7d9f060403a6b475b94164ba1397d6d276751c4144986afe9"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+1/HDF5.v2.0.0.i686-linux-gnu-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[HDF5]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5d1c7db39d685e3444c5c8a0dd578714bc1eafbe"
lazy = true
libgfortran_version = "5.0.0"
mpi = "microsoftmpi"
os = "windows"

    [[HDF5.download]]
    sha256 = "8141c55249d887cc7632705e2a1e6860c0626d26fac023538271373ddbc0bf5b"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+1/HDF5.v2.0.0.i686-w64-mingw32-libgfortran5-cxx11-mpi+microsoftmpi.tar.gz"
[[HDF5]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eeb62c2676ba7ecb510a5c936316e266c20ea897"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[HDF5.download]]
    sha256 = "e4f74e385e5363833888d8a26d87fc646a3d5afc3e04befab81ccbbc53647bb1"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+1/HDF5.v2.0.0.powerpc64le-linux-gnu-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[HDF5]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1ce8c6c5401e748e01581747b58d8c1de29e04c9"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[HDF5.download]]
    sha256 = "5c7f8dfc0a8b8231839c4f324760dc8cd7f9dc33d99afecd1d351ff69107efe5"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+1/HDF5.v2.0.0.powerpc64le-linux-gnu-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[HDF5]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "005ff4587223a9f7bd504c760ea4cef40ac727cf"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[HDF5.download]]
    sha256 = "13585b1b7f9cb76624f50258c8d106fdb123fed94711556b40bd78310c16f11a"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+1/HDF5.v2.0.0.powerpc64le-linux-gnu-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[HDF5]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b304c0ed843f93cb004456895949aa3ef222d4c"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[HDF5.download]]
    sha256 = "2f3e95ce899d6a09b08ca6809e7b8511bfb871be71a096d265ff18392a5a3117"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+1/HDF5.v2.0.0.riscv64-linux-gnu-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[HDF5]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a832d090cae5a7dd3bfe74b319fb68bfb0384205"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[HDF5.download]]
    sha256 = "c5859a608272db6f67ddc0a45ee01d241c74ae64647c3de7098cceeb24d02486"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+1/HDF5.v2.0.0.riscv64-linux-gnu-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[HDF5]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "56a4a2d8eae93a82643925867b01ee6d2dfc0713"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[HDF5.download]]
    sha256 = "958a5a460428b4327771a155c702dbd153466310fb9156302463418a28427828"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+1/HDF5.v2.0.0.riscv64-linux-gnu-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[HDF5]]
arch = "x86_64"
git-tree-sha1 = "80e550c7e7ac77ae3e37394dc3c1e973683c2afc"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[HDF5.download]]
    sha256 = "18a4b4fa6541d6f1df5b2a79af2d9f43bbe409d7713e132478390af92b729d00"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+1/HDF5.v2.0.0.x86_64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[HDF5]]
arch = "x86_64"
git-tree-sha1 = "2fcadfdeb613a29899d756d36c310202b219c32f"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[HDF5.download]]
    sha256 = "154f39619c76a497b891b4299349a6098b05b28c526d17db7225c9ac3bd3c936"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+1/HDF5.v2.0.0.x86_64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[HDF5]]
arch = "x86_64"
git-tree-sha1 = "e45552e8bec18dbe7aa99c7cc864e66edfb5b4d2"
lazy = true
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "macos"

    [[HDF5.download]]
    sha256 = "80edd0942649e70351585f4a8a54d3f487922b97f69482a6ebef1c38d96284be"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+1/HDF5.v2.0.0.x86_64-apple-darwin-libgfortran5-mpi+openmpi.tar.gz"
[[HDF5]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8bf01caab0fe0d9f80962ed3639c6330ef905f07"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[HDF5.download]]
    sha256 = "1770e0985f137baa43640197ed246497607f041ea1cec3d0377d06297443a54a"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+1/HDF5.v2.0.0.x86_64-linux-gnu-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[HDF5]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c266896f6c5ce0574ad987b11cec3070c27af913"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[HDF5.download]]
    sha256 = "a46f5f981c8a5726aa2a9fc0cb65cf2f448d5b2825c9d1bb6fce2bce8331a3ba"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+1/HDF5.v2.0.0.x86_64-linux-gnu-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[HDF5]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a2eb758a886e80dea1e6cbeb3a769bc43840b80"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[HDF5.download]]
    sha256 = "9d92a8bf8def7b81fb1283ed3e892c8c2e1a1955a8c1b39d26fd10e52f9a8a01"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+1/HDF5.v2.0.0.x86_64-linux-gnu-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[HDF5]]
arch = "x86_64"
git-tree-sha1 = "90edacade2c39b836244d461ad8e769d1645a5ff"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "freebsd"

    [[HDF5.download]]
    sha256 = "70ee86af982fe5d10cc69b658c651fcf5ffc6952b1137f3e48709ec59f857a3d"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+1/HDF5.v2.0.0.x86_64-unknown-freebsd-libgfortran5-mpi+mpich.tar.gz"
[[HDF5]]
arch = "x86_64"
git-tree-sha1 = "9b8384820d1e7cf636504b5a2246ce27ade972b5"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "freebsd"

    [[HDF5.download]]
    sha256 = "4ca741f1a36e9d6b4227a95d31d48d53b8095706a647db9c7d7b1cfe76bc9f36"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+1/HDF5.v2.0.0.x86_64-unknown-freebsd-libgfortran5-mpi+mpitrampoline.tar.gz"
[[HDF5]]
arch = "x86_64"
git-tree-sha1 = "fca5eed74e03e953e2f8a21f5b2ca9111dd02a90"
lazy = true
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "freebsd"

    [[HDF5.download]]
    sha256 = "9b6736a4a6c3aaefe7788b05d6a94ecc1d46e2d1c37f6afca329a2bcb72c4092"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+1/HDF5.v2.0.0.x86_64-unknown-freebsd-libgfortran5-mpi+openmpi.tar.gz"
[[HDF5]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2bada31b10f26156cb0052bcb9fe998fe325b280"
lazy = true
libgfortran_version = "5.0.0"
mpi = "microsoftmpi"
os = "windows"

    [[HDF5.download]]
    sha256 = "df1518caed68f4d4aad814e9e7ede86b3755d97fb41d5b0e7e70f9d55d9f9293"
    url = "https://github.com/JuliaBinaryWrappers/HDF5_jll.jl/releases/download/HDF5-v2.0.0+1/HDF5.v2.0.0.x86_64-w64-mingw32-libgfortran5-cxx11-mpi+microsoftmpi.tar.gz"
