# Autogenerated wrapper script for HDF5_jll for armv7l-linux-gnueabihf
export libhdf5, libhdf5_hl

using Zlib_jll
JLLWrappers.@generate_wrapper_header("HDF5")
JLLWrappers.@declare_library_product(libhdf5, "libhdf5.so.103")
JLLWrappers.@declare_library_product(libhdf5_hl, "libhdf5_hl.so.100")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll)
    JLLWrappers.@init_library_product(
        libhdf5,
        "lib/libhdf5.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libhdf5_hl,
        "lib/libhdf5_hl.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
