# Autogenerated wrapper script for HDF5_jll for i686-linux-gnu
export libhdf5, libhdf5_hl

using Zlib_jll
JLLWrappers.@generate_wrapper_header("HDF5")
JLLWrappers.@declare_library_product(libhdf5, "libhdf5-cafdb71e.so.103.0.0")
JLLWrappers.@declare_library_product(libhdf5_hl, "libhdf5_hl-3aef14e1.so.100.1.1")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll)
    JLLWrappers.@init_library_product(
        libhdf5,
        "lib/libhdf5.so.103.0.0",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libhdf5_hl,
        "lib/libhdf5_hl.so.100.1.1",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
