# Autogenerated wrapper script for HDF5_jll for i686-linux-gnu
export libhdf5

using Zlib_jll
## Global variables
PATH = ""
LIBPATH = ""
LIBPATH_env = "LD_LIBRARY_PATH"

# Relative path to `libhdf5`
const libhdf5_splitpath = ["lib", "libhdf5.so.103.0.0"]

# This will be filled out by __init__() for all products, as it must be done at runtime
libhdf5_path = ""

# libhdf5-specific global declaration
# This will be filled out by __init__()
libhdf5_handle = C_NULL

# This must be `const` so that we can use it with `ccall()`
const libhdf5 = "libhdf5-ad97bb1b.so.103.0.0"


"""
Open all libraries
"""
function __init__()
    global prefix = abspath(joinpath(@__DIR__, ".."))

    # Initialize PATH and LIBPATH environment variable listings
    global PATH_list, LIBPATH_list
    append!.(Ref(PATH_list), (Zlib_jll.PATH_list,))
    append!.(Ref(LIBPATH_list), (Zlib_jll.LIBPATH_list,))

    global libhdf5_path = abspath(joinpath(artifact"HDF5", libhdf5_splitpath...))

    # Manually `dlopen()` this right now so that future invocations
    # of `ccall` with its `SONAME` will find this path immediately.
    global libhdf5_handle = dlopen(libhdf5_path)
    push!(LIBPATH_list, dirname(libhdf5_path))

    # Filter out duplicate and empty entries in our PATH and LIBPATH entries
    filter!(!isempty, unique!(PATH_list))
    filter!(!isempty, unique!(LIBPATH_list))
    global PATH = join(PATH_list, ':')
    global LIBPATH = join(LIBPATH_list, ':')

    # Add each element of LIBPATH to our DL_LOAD_PATH (necessary on platforms
    # that don't honor our "already opened" trick)
    #for lp in LIBPATH_list
    #    push!(DL_LOAD_PATH, lp)
    #end
end  # __init__()

